name = "KAEM"
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BFloat16s = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ConfParser = "88353bc9-fd38-507d-a820-d3b43837d6b9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Embeddings = "c5bfea45-b7f1-5224-a596-15500f5db411"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HuggingFaceDatasets = "d94b9a45-fdf5-4270-b024-5cbb9ef7117d"
HyperTuning = "ddfa78db-9111-4329-a6bd-d4ed85ceb229"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Runic = "62bfec6d-59d7-401d-8490-b29ee721c001"

[compat]
BenchmarkTools = "1.6"
CSV = "0.10"
ComponentArrays = "0.15"
ConfParser = "0.1"
DataFrames = "1.7"
Distributions = "0.25"
FastGaussQuadrature = "1.0"
HDF5 = "0.17"
ImageTransformations = "0.10"
Images = "0.26"
JET = "0.9"
JLD2 = "0.5"
LaTeXStrings = "1.4"
LineSearches = "7.4"
MLDatasets = "0.7"
Optimisers = "0.4.6"
Plots = "1.40"
Reactant = "0.2.181"
julia = "1.11"
